import sys
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, TextStreamer

def main():
    print("==================================================")
    print(" Local Interactive FP8 Llama CLI Chat ")
    print("==================================================\n")

    # 1. Жесткая проверка CUDA перед стартом
    if not torch.cuda.is_available():
        print("\n[CRITICAL ERROR]: PyTorch is not using CUDA!")
        print("Please install the GPU version via: pip install torch --index-url https://download.pytorch.org/whl/cu124")
        return

    print(f"[Hardware] GPU detected: {torch.cuda.get_device_name(0)}")
    print(f"[Hardware] Allocated VRAM before load: {torch.cuda.memory_allocated(0) / (1024**2):.1f} MB\n")

    model_path = "./llama3-8b-fp8"

    print("[System] Loading tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(model_path)

    print("[System] Pushing FP8 weights directly to RTX 5070 VRAM...")
    
    # 2. Принудительный маппинг только в VRAM (запрещает тихий сброс в RAM)
    model = AutoModelForCausalLM.from_pretrained(
        model_path,
        device_map={"": "cuda:0"},  # Жестко требуем 100% загрузки на GPU
        torch_dtype="auto"
    )

    # Initialize the streamer to print tokens instantly without buffering
    streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)

    print("\n[System] Model loaded successfully! Active VRAM setup is ready.")
    print("[System] Type 'exit' or 'quit' to end the session.\n")
    print("--------------------------------------------------")

    # Maintain full conversation context
    messages = [
        {"role": "system", "content": "You are a highly intelligent, concise, and helpful AI assistant."}
    ]

    while True:
        try:
            user_input = input("\n[User]: ")
            
            # Check for exit commands
            if user_input.lower().strip() in ["exit", "quit"]:
                print("\n[System] Closing chat session. Goodbye!")
                break
            
            # Skip empty inputs
            if not user_input.strip():
                continue

            # Append the new user input to the conversation history
            messages.append({"role": "user", "content": user_input})

            # Apply the standard Llama 3 / 3.1 chat template
            inputs = tokenizer.apply_chat_template(
                messages,
                add_generation_prompt=True,
                return_tensors="pt"
            ).to(model.device)

            print("\n[Llama]: ", end="", flush=True)

            # Generate the response with active streaming
            with torch.no_grad():
                output_ids = model.generate(
                    inputs,
                    max_new_tokens=1024,
                    streamer=streamer,
                    do_sample=True,         # Enable sampling for natural conversation
                    temperature=0.6,        # Balanced creativity and precision
                    top_p=0.9,
                    pad_token_id=tokenizer.eos_token_id
                )

            # Extract exactly the new tokens generated by the assistant
            generated_ids = output_ids[0][inputs.shape[1]:]
            response_text = tokenizer.decode(generated_ids, skip_special_tokens=True)

            # Save the model's response to the history so it remembers context next turn
            messages.append({"role": "assistant", "content": response_text.strip()})

        except KeyboardInterrupt:
            # Handle Ctrl+C gracefully without crashing the terminal
            print("\n\n[System] Current generation interrupted. Type 'exit' to quit.")
            continue
        except Exception as e:
            print(f"\n[Critical Error]: {e}")
            break

if __name__ == "__main__":
    main()