# Generates the hardcoded golden arrays embedded in test_tokenizer_golden.cpp.
# Run:  python tests/integration/generate_tokenizer_goldens.py > goldens.inc
# Requires: transformers + local checkpoints (same paths as the engine tests).
#
# The output is C++ source: a table of {text, ids_no_special, ids_with_special}
# per model plus chat-template token sequences. Regenerate and re-paste into the
# test whenever the test strings change.
import json
import sys

from transformers import AutoTokenizer

MODELS = {
    "llama3": "F:/AI/llama3-8b-fp8",
    "qwen25": "F:/AI/Qwen2.5-Coder-7B-Instruct-AWQ",
}

# Exercises: plain ASCII, punctuation, Cyrillic UTF-8, code with indentation,
# digit runs (Llama groups {1,3}, Qwen splits single digits), contractions
# (the (?i:'s|'t|...) branch), mixed/trailing whitespace and emoji.
TEXTS = [
    "Hello, world!",
    "The quick brown fox jumps over the lazy dog.",
    "Привет, мир! Как дела?",
    "def fibonacci(n):\n    return n if n < 2 else fibonacci(n-1) + fibonacci(n-2)",
    "Pi is 3.14159265358979, e is 2.71828",
    "  leading spaces and\n\nnewlines\t tabs   ",
    "I'd've thought it's GPT-4's win, isn't it?",
    "🚀 émigré naïve café",
]

CHAT = [
    {"role": "system", "content": "You are a helpful assistant."},
    {"role": "user", "content": "Write hello world in C++."},
    {"role": "assistant", "content": 'std::cout << "Hello, world!\\n";'},
    {"role": "user", "content": "Now in Rust."},
]

CHAT_NO_SYSTEM = [
    {"role": "user", "content": "What is 2+2?"},
]


def cpp_str(s: str) -> str:
    out = s.encode("unicode_escape").decode("ascii").replace('"', '\\"')
    # unicode_escape emits \xNN / \uNNNN; C++ needs the raw UTF-8 bytes instead.
    return json.dumps(s, ensure_ascii=False)


def emit_ids(name: str, ids) -> None:
    if not isinstance(ids, list):  # newer transformers return a BatchEncoding
        ids = ids["input_ids"]
    print(f"const std::vector<int> {name} = {{{', '.join(map(str, ids))}}};")


def main() -> None:
    print("// AUTO-GENERATED by generate_tokenizer_goldens.py -- do not edit by hand.")
    for tag, path in MODELS.items():
        tok = AutoTokenizer.from_pretrained(path)
        print(f"\n// ==== {tag} ({path}) ====")
        print(f"const GoldenEncodeCase k_{tag}_encode_cases[] = {{")
        for text in TEXTS:
            plain = tok.encode(text, add_special_tokens=False)
            special = tok.encode(text, add_special_tokens=True)
            print(f"    {{{cpp_str(text)},")
            print(f"     {{{', '.join(map(str, plain))}}},")
            print(f"     {{{', '.join(map(str, special))}}}}},")
        print("};")

        chat_ids = tok.apply_chat_template(CHAT, add_generation_prompt=True)
        emit_ids(f"k_{tag}_chat_ids", chat_ids)
        rendered = tok.apply_chat_template(CHAT, add_generation_prompt=True, tokenize=False)
        print(f"// rendered: {json.dumps(rendered, ensure_ascii=False)}")

        nosys_ids = tok.apply_chat_template(CHAT_NO_SYSTEM, add_generation_prompt=True)
        emit_ids(f"k_{tag}_chat_nosys_ids", nosys_ids)
        rendered = tok.apply_chat_template(CHAT_NO_SYSTEM, add_generation_prompt=True, tokenize=False)
        print(f"// rendered: {json.dumps(rendered, ensure_ascii=False)}")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    main()
