// Golden verification of the tokenizer subsystem against the two real
// checkpoints the engine targets:
//   - Llama-3.1-8B-FP8 (BOS post-processor, \p{N}{1,3} digit runs, llama3
//     header chat template with knowledge-cutoff preamble)
//   - Qwen2.5-Coder-7B-Instruct-AWQ (no BOS, single-digit runs, ChatML with
//     default system prompt injection)
// Expected ids were produced by HuggingFace transformers via
// generate_tokenizer_goldens.py; regenerate with that script if the test
// strings change. Tests skip when a checkpoint is not present locally
// (override the directories with BLACKWELL_LLAMA_DIR / BLACKWELL_QWEN_DIR).
#include <gtest/gtest.h>

#include <cstdlib>
#include <filesystem>
#include <memory>
#include <string>
#include <vector>

#include "blackwell/tokenizer.h"

using blackwell::ChatMessage;
using blackwell::ITokenizer;
using blackwell::TokenizerFactory;

namespace {

std::string env_or(const char* name, const char* fallback) {
    const char* v = std::getenv(name);
    return v && *v ? v : fallback;
}

std::string llama_dir() { return env_or("BLACKWELL_LLAMA_DIR", "F:/AI/llama3-8b-fp8"); }
std::string qwen_dir() {
    return env_or("BLACKWELL_QWEN_DIR", "F:/AI/Qwen2.5-Coder-7B-Instruct-AWQ");
}

bool has_tokenizer(const std::string& dir) {
    return std::filesystem::exists(std::filesystem::path(dir) / "tokenizer.json");
}

struct GoldenEncodeCase {
    const char* text;
    std::vector<int> plain;        // add_special_tokens = false
    std::vector<int> with_special; // add_special_tokens = true
};

// ---- goldens generated by generate_tokenizer_goldens.py ---------------------

const GoldenEncodeCase k_llama3_encode_cases[] = {
    {"Hello, world!",
     {9906, 11, 1917, 0},
     {128000, 9906, 11, 1917, 0}},
    {"The quick brown fox jumps over the lazy dog.",
     {791, 4062, 14198, 39935, 35308, 927, 279, 16053, 5679, 13},
     {128000, 791, 4062, 14198, 39935, 35308, 927, 279, 16053, 5679, 13}},
    {"Привет, мир! Как дела?",
     {54745, 28089, 8341, 11, 115388, 0, 107234, 123936, 30},
     {128000, 54745, 28089, 8341, 11, 115388, 0, 107234, 123936, 30}},
    {"def fibonacci(n):\n    return n if n < 2 else fibonacci(n-1) + fibonacci(n-2)",
     {755, 76798, 1471, 997, 262, 471, 308, 422, 308, 366, 220, 17, 775, 76798, 1471, 12, 16, 8, 489, 76798, 1471, 12, 17, 8},
     {128000, 755, 76798, 1471, 997, 262, 471, 308, 422, 308, 366, 220, 17, 775, 76798, 1471, 12, 16, 8, 489, 76798, 1471, 12, 17, 8}},
    {"Pi is 3.14159265358979, e is 2.71828",
     {35867, 374, 220, 18, 13, 9335, 20128, 21598, 22905, 4643, 11, 384, 374, 220, 17, 13, 21982, 1591},
     {128000, 35867, 374, 220, 18, 13, 9335, 20128, 21598, 22905, 4643, 11, 384, 374, 220, 17, 13, 21982, 1591}},
    {"  leading spaces and\n\nnewlines\t tabs   ",
     {220, 6522, 12908, 323, 271, 943, 8128, 197, 23204, 262},
     {128000, 220, 6522, 12908, 323, 271, 943, 8128, 197, 23204, 262}},
    {"I'd've thought it's GPT-4's win, isn't it?",
     {40, 4265, 3077, 3463, 433, 596, 480, 2898, 12, 19, 596, 3243, 11, 4536, 956, 433, 30},
     {128000, 40, 4265, 3077, 3463, 433, 596, 480, 2898, 12, 19, 596, 3243, 11, 4536, 956, 433, 30}},
    {"🚀 émigré naïve café",
     {9468, 248, 222, 4046, 76, 5346, 978, 95980, 588, 53050},
     {128000, 9468, 248, 222, 4046, 76, 5346, 978, 95980, 588, 53050}},
};

const std::vector<int> k_llama3_chat_ids = {128000, 128006, 9125, 128007, 271, 38766, 1303, 33025, 2696, 25, 6790, 220, 2366, 18, 198, 15724, 2696, 25, 220, 1627, 10263, 220, 2366, 19, 271, 2675, 527, 264, 11190, 18328, 13, 128009, 128006, 882, 128007, 271, 8144, 24748, 1917, 304, 356, 23740, 128009, 128006, 78191, 128007, 271, 1872, 487, 6232, 1134, 330, 9906, 11, 1917, 15114, 77, 5233, 128009, 128006, 882, 128007, 271, 7184, 304, 34889, 13, 128009, 128006, 78191, 128007, 271};
const std::vector<int> k_llama3_chat_nosys_ids = {128000, 128006, 9125, 128007, 271, 38766, 1303, 33025, 2696, 25, 6790, 220, 2366, 18, 198, 15724, 2696, 25, 220, 1627, 10263, 220, 2366, 19, 271, 128009, 128006, 882, 128007, 271, 3923, 374, 220, 17, 10, 17, 30, 128009, 128006, 78191, 128007, 271};

const GoldenEncodeCase k_qwen25_encode_cases[] = {
    {"Hello, world!",
     {9707, 11, 1879, 0},
     {9707, 11, 1879, 0}},
    {"The quick brown fox jumps over the lazy dog.",
     {785, 3974, 13876, 38835, 34208, 916, 279, 15678, 5562, 13},
     {785, 3974, 13876, 38835, 34208, 916, 279, 15678, 5562, 13}},
    {"Привет, мир! Как дела?",
     {53645, 26991, 8178, 11, 137144, 0, 128654, 129691, 30},
     {53645, 26991, 8178, 11, 137144, 0, 128654, 129691, 30}},
    {"def fibonacci(n):\n    return n if n < 2 else fibonacci(n-1) + fibonacci(n-2)",
     {750, 75698, 1445, 982, 262, 470, 308, 421, 308, 366, 220, 17, 770, 75698, 1445, 12, 16, 8, 488, 75698, 1445, 12, 17, 8},
     {750, 75698, 1445, 982, 262, 470, 308, 421, 308, 366, 220, 17, 770, 75698, 1445, 12, 16, 8, 488, 75698, 1445, 12, 17, 8}},
    {"Pi is 3.14159265358979, e is 2.71828",
     {34767, 374, 220, 18, 13, 16, 19, 16, 20, 24, 17, 21, 20, 18, 20, 23, 24, 22, 24, 11, 384, 374, 220, 17, 13, 22, 16, 23, 17, 23},
     {34767, 374, 220, 18, 13, 16, 19, 16, 20, 24, 17, 21, 20, 18, 20, 23, 24, 22, 24, 11, 384, 374, 220, 17, 13, 22, 16, 23, 17, 23}},
    {"  leading spaces and\n\nnewlines\t tabs   ",
     {220, 6388, 12621, 323, 271, 931, 7969, 197, 22398, 262},
     {220, 6388, 12621, 323, 271, 931, 7969, 197, 22398, 262}},
    {"I'd've thought it's GPT-4's win, isn't it?",
     {40, 4172, 3003, 3381, 432, 594, 479, 2828, 12, 19, 594, 3164, 11, 4436, 944, 432, 30},
     {40, 4172, 3003, 3381, 432, 594, 479, 2828, 12, 19, 594, 3164, 11, 4436, 944, 432, 30}},
    {"🚀 émigré naïve café",
     {145836, 3958, 76, 5233, 963, 94880, 586, 51950},
     {145836, 3958, 76, 5233, 963, 94880, 586, 51950}},
};

const std::vector<int> k_qwen25_chat_ids = {151644, 8948, 198, 2610, 525, 264, 10950, 17847, 13, 151645, 198, 151644, 872, 198, 7985, 23811, 1879, 304, 356, 22890, 151645, 198, 151644, 77091, 198, 1834, 486, 6104, 1115, 330, 9707, 11, 1879, 14771, 77, 5123, 151645, 198, 151644, 872, 198, 7039, 304, 33789, 13, 151645, 198, 151644, 77091, 198};
const std::vector<int> k_qwen25_chat_nosys_ids = {151644, 8948, 198, 2610, 525, 1207, 16948, 11, 3465, 553, 54364, 14817, 13, 1446, 525, 264, 10950, 17847, 13, 151645, 198, 151644, 872, 198, 3838, 374, 220, 17, 10, 17, 30, 151645, 198, 151644, 77091, 198};

// Same conversations generate_tokenizer_goldens.py fed to HuggingFace.
const std::vector<ChatMessage> k_chat = {
    {"system", "You are a helpful assistant."},
    {"user", "Write hello world in C++."},
    {"assistant", "std::cout << \"Hello, world!\\n\";"},
    {"user", "Now in Rust."},
};
const std::vector<ChatMessage> k_chat_nosys = {{"user", "What is 2+2?"}};

// ---- shared test body --------------------------------------------------------

class TokenizerGolden : public ::testing::TestWithParam<const char*> {
protected:
    void SetUp() override {
        const std::string dir = GetParam() == std::string("llama3") ? llama_dir() : qwen_dir();
        if (!has_tokenizer(dir))
            GTEST_SKIP() << "tokenizer.json not found under " << dir
                         << " (set BLACKWELL_LLAMA_DIR / BLACKWELL_QWEN_DIR to override)";
        tokenizer_ = TokenizerFactory::create(dir);
    }

    const GoldenEncodeCase* cases() const {
        return GetParam() == std::string("llama3") ? k_llama3_encode_cases
                                                   : k_qwen25_encode_cases;
    }
    size_t case_count() const {
        return GetParam() == std::string("llama3")
                   ? std::size(k_llama3_encode_cases)
                   : std::size(k_qwen25_encode_cases);
    }

    std::unique_ptr<ITokenizer> tokenizer_;
};

TEST_P(TokenizerGolden, EncodeMatchesHuggingFace) {
    for (size_t i = 0; i < case_count(); ++i) {
        const auto& c = cases()[i];
        EXPECT_EQ(tokenizer_->encode(c.text, false), c.plain) << "text: " << c.text;
        EXPECT_EQ(tokenizer_->encode(c.text, true), c.with_special)
            << "text (with specials): " << c.text;
    }
}

TEST_P(TokenizerGolden, DecodeRoundTripsExactly) {
    // Byte-level BPE is lossless: decode(encode(x)) must reproduce x byte-for-byte.
    for (size_t i = 0; i < case_count(); ++i) {
        const auto& c = cases()[i];
        EXPECT_EQ(tokenizer_->decode(tokenizer_->encode(c.text, false)), c.text);
    }
}

TEST_P(TokenizerGolden, ChatTemplateMatchesHuggingFace) {
    ASSERT_NE(tokenizer_->chat_template(), nullptr);
    const bool is_llama = GetParam() == std::string("llama3");
    EXPECT_EQ(tokenizer_->apply_chat_template(k_chat, true),
              is_llama ? k_llama3_chat_ids : k_qwen25_chat_ids);
    // No system message: Llama-3 still emits its dated system block, ChatML
    // injects the default prompt extracted from the Jinja source.
    EXPECT_EQ(tokenizer_->apply_chat_template(k_chat_nosys, true),
              is_llama ? k_llama3_chat_nosys_ids : k_qwen25_chat_nosys_ids);
}

TEST_P(TokenizerGolden, IncrementalChatApiComposesToFullConversation) {
    std::vector<int> ids = tokenizer_->encode_chat_prelude(k_chat[0].content);
    for (size_t i = 1; i < k_chat.size(); ++i) {
        const auto turn = tokenizer_->encode_chat_message(k_chat[i]);
        ids.insert(ids.end(), turn.begin(), turn.end());
    }
    const auto gen = tokenizer_->encode_generation_prompt();
    ids.insert(ids.end(), gen.begin(), gen.end());
    EXPECT_EQ(ids, tokenizer_->apply_chat_template(k_chat, true));
}

INSTANTIATE_TEST_SUITE_P(Checkpoints, TokenizerGolden,
                         ::testing::Values("llama3", "qwen25"),
                         [](const auto& info) { return std::string(info.param); });

// ---- per-model special-token resolution -------------------------------------

TEST(TokenizerGoldenLlama, SpecialTokensResolvedFromConfigs) {
    if (!has_tokenizer(llama_dir())) GTEST_SKIP() << "Llama checkpoint not present";
    const auto tok = TokenizerFactory::create(llama_dir());

    const auto& st = tok->special_tokens();
    EXPECT_EQ(st.bos, tok->token_to_id("<|begin_of_text|>"));
    EXPECT_EQ(st.eos, tok->token_to_id("<|eot_id|>"));
    // config.json eos_token_id list = {end_of_text, eom_id, eot_id}.
    EXPECT_EQ(st.stop_ids.size(), 3u);
    for (const int id : st.stop_ids) EXPECT_TRUE(tok->is_special(id));
    EXPECT_TRUE(tok->is_stop(st.eos));

    // BOS comes from the post-processor when add_special_tokens=true.
    const auto ids = tok->encode("hi", true);
    ASSERT_FALSE(ids.empty());
    EXPECT_EQ(ids.front(), st.bos);
    EXPECT_EQ(tok->decode(st.bos), "");
    EXPECT_EQ(tok->decode(st.bos, true), "<|begin_of_text|>");
}

TEST(TokenizerGoldenQwen, SpecialTokensResolvedFromConfigs) {
    if (!has_tokenizer(qwen_dir())) GTEST_SKIP() << "Qwen checkpoint not present";
    const auto tok = TokenizerFactory::create(qwen_dir());

    const auto& st = tok->special_tokens();
    // tokenizer_config.json says bos_token: null, but config.json still
    // declares bos_token_id (= <|endoftext|>); the factory falls back to it.
    // What matters is that no BOS is ever *injected* (asserted below).
    EXPECT_EQ(st.bos, tok->token_to_id("<|endoftext|>"));
    EXPECT_EQ(st.eos, tok->token_to_id("<|im_end|>"));
    // generation_config.json stop set: {<|im_end|>, <|endoftext|>}.
    EXPECT_EQ(st.stop_ids.size(), 2u);
    EXPECT_TRUE(tok->is_stop(tok->token_to_id("<|im_end|>")));
    EXPECT_TRUE(tok->is_stop(tok->token_to_id("<|endoftext|>")));

    // No post-processor inserts: add_special_tokens is a no-op.
    EXPECT_EQ(tok->encode("hi", true), tok->encode("hi", false));

    // Special-token strings in raw text resolve to their ids.
    const auto ids = tok->encode("<|im_start|>user\nhi<|im_end|>", false);
    ASSERT_GE(ids.size(), 2u);
    EXPECT_EQ(ids.front(), tok->token_to_id("<|im_start|>"));
    EXPECT_EQ(ids.back(), tok->token_to_id("<|im_end|>"));
}

} // namespace
